name: cam_we_go
description: "A road sign and road state mobile notification application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/logo.png
    - assets/images/introduction_image.png
